### ISSUE TITLE
Dynamically updating cluster geojson source - UI lags behind

### ISSUE THREAD

**Issue by HarelM** [Wykks/ngx-mapbox-gl#206]
I'm trying to upgrade from version `3.3.0` where I used the deprecated `mgl-marker-cluster` to 4.3.
The problem I'm facing is that my cluster source is updating dynamically when panning the map - getting points from the server on each map move.
Unfortunately, now that I have changed my code to use the latest version the map updates is lagging behind - i.e. I move the map, the data is fetched, the source is updated but the map is not updated with latest changes.
When I move the map again (very fine movement for debug sake) the marker are presented.
Is there a way to make the cluster refresh or something?
This is the only thing that prevents me from upgrading to 4.3 ... :-/

**Comment by HarelM** [comment]
Reproduction can be seen here:
https://stackblitz.com/edit/ngx-mapbox-gl-issue-206
When the map loads the source has some elements.
Over time the items are added (I have done this using an interval) but the cluster does not get updated.
Only when moving the map the cluster updates.
Is there a workaround to this issue I can use?

**Comment by HarelM** [comment]
I'm getting more than one update of my data when assigning the source with new data so the problem might be with the `take(1)`?
https://github.com/Wykks/ngx-mapbox-gl/blob/1cae360de33188ddc578360991c002eb7f0c7d1a/projects/ngx-mapbox-gl/src/lib/markers-for-clusters/markers-for-clusters.component.ts#L77
Not sure... I have a hard time debugging/testing this...

**Comment by HarelM** [comment]
Nope, seems like there's more complexity involved as I see that sometimes `data` event with `isSourceLoaded` never gets fired, not sure why or how...
Seems like the best workaround I can think of is to use throttle or something just to disable too many event fired. But that's just a nasty hack... :-/

**Comment by dmytro-gokun** [comment]
@HarelM The original library author (Wykks) does not have time to support it. I'm doing the most of support these days. However, i'm not really familiar with cluster-related part of the lib. Mostly because I did not have a chance to use it.  So, i think the best option would be if someone who has interested in it, stepped in and proposed a good fix (not a hack) to the lib. If you have time and feel you can do it - you are very welcome.

**Comment by HarelM** [comment]
@dmytro-gokun thanks for the info!
The main problem I see is that I'm not sure the problem is with the complexity of my code or the code that is written here.
Although I managed to create a simple reproduction I'm not sure that fixing it will solve the general case I'm facing.
I'd love to help out as much as I can, and willing to submit a pull request to fixing this bug (assuming I'll find a good solution, or at least a solution that doesn't fill like a hack).
If you have more info about the reason this new cluster was introduced instead of the old one or the design behind the new component you can share with me it'll help a lot.
besides this, of course:
https://github.com/Wykks/ngx-mapbox-gl/pull/151

Also the docs about the cluster needs to be updated. I can take care of that as well assuming the only thing I need to do is change the wiki page. If not, please let me know.

**Comment by dmytro-gokun** [comment]
@HarelM Unfortunatelly, I do not have much to add here. One thing i can see is this PR comment: "This remove direct dependency of supercluster and improve marker performance". That probably answers the question "why".

> Also the docs about the cluster needs to be updated. I can take care of that as well assuming the only thing I need to do is change the wiki page. If not, please let me know.

That will be really appreciated. As far as I can see, we only have that info on Wiki. Also, in README.md we have this reference to Wiki:

```
- [mgl-marker-cluster](https://github.com/Wykks/ngx-mapbox-gl/wiki/API-Documentation#ngx-mgl-marker-cluster-supercluster-api)
```

As long as this link stays alive, we are good to go with Wiki-only changes.

**Comment by HarelM** [comment]
Ok, thanks! I don't think I have permissions to update the wiki though. I need to do it using a PR?
Also I saw that the gh-pages branch which is responsible for the io site is checked-in, do you know how it was generated?

**Comment by dmytro-gokun** [comment]
@HarelM It appears wiki editing is only enabled for project collaborators. The easiest way to do it right now would be for you to send edits to me and i will put them in.

In the mean time... @Wykks Do you think it makes sense to enable Wiki editing for everyone? Or do you know a better way of accepting edits from folks (w/o having to send chunks of text around to collaborators)?

> Also I saw that the gh-pages branch which is responsible for the io site is checked-in, do you know how it was generated?

It's maintained automatically by the "ngh" tool. One of the collaborators has to call it manually when they want to publish the showcase page.

NB. If you plan on creating PRs, plz read this: https://github.com/Wykks/ngx-mapbox-gl/blob/master/DEVELOPER.md
Let me know if you have any further questions.

**Comment by HarelM** [comment]
@dmytro-gokun Ok, thanks!
I'll send you the relevant text here for you to update later today.
I have looked at recent commits just to see how things are done and found the developer.md and show-case stuff, so what you just wrote is aligned with what I understood.
Just a side note, I saw that you have added `locale` support but it is not documented in the wiki API.
I don't know if I'm the only one who reads this documentation, but I find it extremely faster to read this instead of looking at examples (I look at examples usually when things don't work straight for me)...
Keep up the good work!

**Comment by dmytro-gokun** [comment]
@HarelM You are absolutely right. We miss some stuff on Wiki. Especially the stuff added recently. If you could help with updating that it would be really nice.

**Comment by HarelM** [comment]
Updated documentation for clusters are below: As you said, I don't have permission to update the wiki so you'll need to do it - I'm not aware of all the changes that was made recently, I just looked at a few recent commits. Since you are the main maintainer of this library I'm sure it wouldn't be hard for you to update the wiki with your recent changes :-)

## [ngx] mgl-markers-for-clusters
Requires a geojson source that is clustered - see above. This replaced `mgl-marker-cluster` that was used in version 3.x.
### Example

```html
...
<mgl-map
  ...
>
    <mgl-markers--for-cluster
     [source]="myGeoJsonclusteredSource"
    >
      <ng-template mglPoint let-feature>
        Marker!
      </ng-template>
      <ng-template mglClusterPoint let-feature>
        ClusterId: {{feature.properties?.cluster_id}}, Points: {{feature.properties?.point_count}}
      </ng-template>
    </mgl-markers--for-cluster>
</mgl-map>
```
Note: Only use this if you really need to use HTML/Angular component to render your symbols. This is slower than the native cluster system that can be used using a clustered source and styling layers.

### Inputs
init only:
 * **source:** `string | Source`

**Comment by Wykks** [comment]
Hi !
Sorry for the long silence here. I believe the wiki should be moved into the repository directly in order to be able to accept doc PR. Using wiki functionality was a mistake.

I may be able to work on this lib again soon if things continue to settle down in my life. Thank you for everything you've done here @dmytro-gokun

**Comment by HarelM** [comment]
@Wykks thanks for stepping up!
I have done some test with the mapbox events to see which are relevant and which are not and I'm not sure I truly understand the event sequence.
From very few tests I made it seems that sometimes the `data` event is called with `isSourceLoaded=false` but there's no event fired with `isSourceLoaded=true` afterwards.
The following is the code I ended up using, which only relays on `data` event as my cluster source is updated on `moveend` so I didn't need the `move` and `moveend` events.
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/components/map/layers-view.component.ts#L95L108

Let me know when there's a version I cant test to see that it solves my use case.
The use case I added here is very simple and I'm not sure it demonstrates all possible scenarios that are related to dynamic cluster.

**Comment by Wykks** [comment]
Hum... Looks like in the end, all it took was to remove `take(1)` :sweat_smile: 

> Nope, seems like there's more complexity involved as I see that sometimes `data` event with `isSourceLoaded` never gets fired, not sure why or how...
> Seems like the best workaround I can think of is to use throttle or something just to disable too many event fired. But that's just a nasty hack... :-/

That's weird, I never encountered this (using mapbox-gl@1.6.0) during my testing...

I'll release a new version with this change today (no need to do a "private" release just for this, it's harmless). Let me know if this worked for you :)

**Comment by HarelM** [comment]
Thanks for the quick fix and release, however this doesn't solve my issue.
I got an error I couldn't understand when upgrading the package on stackblitz to 4.4.0.
In any case, please let me know if the following is working as expected using 4.4.0:
https://stackblitz.com/edit/ngx-mapbox-gl-issue-206-moveend
The following is basically the relevant component - is should update the cluster 1 second after you finish moving the map.
```ts
import {
  Component,
  Input,
  OnInit,
  OnChanges,
  ViewChild,
  SimpleChanges,
  AfterViewInit,
  NgZone
} from "@angular/core";
import { MatPaginator, PageEvent } from "@angular/material/paginator";
import { GeoJSONSourceComponent, MapComponent } from "ngx-mapbox-gl";

/**
 * Remember: mgl-layer are way faster than html markers
 * Html markers are fine if you don't have lots of points
 * Try to draw your point with a mgl-layer before using html markers
 * For a compromise, look at cluster-html example, which use only html markers for cluster points
 */

@Component({
  selector: "showcase-demo",
  template: `
    <mgl-map
      #map
      style="mapbox://styles/mapbox/dark-v9"
      [zoom]="[11]"
      [center]="[-103.59179687498357, 40.66995747013945]"
    >
      <ng-container *ngIf="earthquakes">
        <mgl-geojson-source
          #clusterComponent
          id="earthquakes"
          [data]="earthquakes"
          [cluster]="true"
          [clusterRadius]="50"
          [clusterMaxZoom]="14"
        ></mgl-geojson-source>
        <mgl-markers-for-clusters source="earthquakes">
          <ng-template mglPoint let-feature>
            <div class="marker">
              {{ feature.properties.id }}
            </div>
          </ng-template>
          <ng-template mglClusterPoint let-feature>
            <div
              class="marker-cluster"
              (click)="selectCluster($event, feature)"
            >
              {{ feature.properties?.point_count }}
            </div>
          </ng-template>
        </mgl-markers-for-clusters>
        <mgl-popup *ngIf="selectedCluster" [feature]="selectedCluster">
          <showcase-cluster-popup
            [clusterComponent]="clusterComponent"
            [selectedCluster]="selectedCluster"
          ></showcase-cluster-popup>
        </mgl-popup>
      </ng-container>
    </mgl-map>
  `,
  styleUrls: ["./app.component.css"]
})
export class NgxClusterHtmlComponent implements OnInit, AfterViewInit {
  earthquakes: object;
  selectedCluster: { geometry: GeoJSON.Point; properties: any };
  private index = 10;
  @ViewChild("map")
  public map: MapComponent;

  constructor(private readonly ngZone: NgZone) {}

  public ngOnInit() {
    this.earthquakes = this.updateCluster(this.index);
  }

  selectCluster(event: MouseEvent, feature: any) {
    event.stopPropagation(); // This is needed, otherwise the popup will close immediately
    // Change the ref, to trigger mgl-popup onChanges (when the user click on the same cluster)
    this.selectedCluster = {
      geometry: feature.geometry,
      properties: feature.properties
    };
  }

  public ngAfterViewInit() {
    this.map.load.subscribe(() => {
      this.map.mapInstance.on("moveend", () => {
        setTimeout(() => {
          // this is here to simulate a call to the server on move end that should take a bit of time.
          this.index += 10;
          this.earthquakes = this.updateCluster(this.index);
          console.log(
            "earthquack is not with: " + this.earthquakes.features.length
          );
        }, 1000);
      });
    });
  }

  private updateCluster(index: number) {
    let center = [-103.59179687498357, 40.66995747013945];
    let features = [];
    for (let i = 0; i < index; i++) {
      features.push({
        type: "Point",
        id: i,
        properties: {
          id: i,
          "Secondary ID": "Secondary ID",
          "Primary ID": "Primary ID"
        },
        geometry: {
          coordinates: [center[0] + i / 1000.0, center[1]]
        }
      });
    }
    return { features: features, type: "FeatureCollection" };
  }
}

@Component({
  selector: "showcase-cluster-popup",
  template: `
    <mat-list>
      <mat-list-item *ngFor="let leaf of leaves">
        {{ leaf.properties["Primary ID"] }}
      </mat-list-item>
    </mat-list>
    <mat-paginator
      [length]="selectedCluster.properties?.point_count"
      [pageSize]="5"
      (page)="changePage($event)"
    ></mat-paginator>
  `
})
export class ClusterPopupComponent implements OnChanges {
  @Input() selectedCluster: { geometry: GeoJSON.Point; properties: any };
  @Input() clusterComponent: GeoJSONSourceComponent;

  @ViewChild(MatPaginator, { static: true }) paginator: MatPaginator;

  leaves: GeoJSON.Feature<GeoJSON.Geometry>[];

  ngOnChanges(changes: SimpleChanges) {
    this.changePage();
    if (changes.selectedCluster && !changes.selectedCluster.isFirstChange()) {
      this.paginator.firstPage();
    }
  }

  async changePage(pageEvent?: PageEvent) {
    let offset = 0;
    if (pageEvent) {
      offset = pageEvent.pageIndex * 5;
    }
    this.leaves = await this.clusterComponent.getClusterLeaves(
      this.selectedCluster.properties!.cluster_id,
      5,
      offset
    );
  }
}
```

**Comment by HarelM** [comment]
I can't fully figure this out... :-( See if you can understand why updating to 4.4 breaks stackblitz and I'll try to reproduce the issue I'm experiencing.
The `data` event is fired and `isSourceLoaded=true` but still the cluster is not drawn. might be something with the switchmap, I don't know...

**Comment by Wykks** [comment]
Oh well......... Of course. This time I skipped my usual simple external app testing because it's ok most of the time. And of course, I managed to make a code that only work in the showcase project.
I guess that's deserved, because I didn't touch this project for a long time :sweat_smile: 

Long story short : I screwed up, it's fixed now :D

Also , in your code, you're using the mapbox object directly.
ngx-mapbox-gl run outside ngZone for perf reason. I need to re-evaluate this, and if it's still relevant, I planned to add an option to activate this with an option. Because, yeah, it's confusing...

You should either wrap your code inside `zone.run` or call `detectChanges` or use output of `mgl-map`.
```
        setTimeout(() => {
          // this is here to simulate a call to the server on move end that should take a bit of time.
          this.index += 10;
          this.earthquakes = this.updateCluster(this.index);
          console.log(
            "earthquakes is now with: " + this.earthquakes.features.length
          );
        }, 1000);
```
==>
```
        this.ngZone.run(() => {
          setTimeout(() => {
            // this is here to simulate a call to the server on move end that should take a bit of time.
            this.index += 10;
            this.earthquakes = this.updateCluster(this.index);
            console.log('earthquakes is now with: ' + this.earthquakes.features.length);
          }, 1000);
        })
```

**Comment by HarelM** [comment]
Yea, I figured out the `ngZone` yesterday night too (forgot to update the stackblitz though) and also added it to my code as I thought it was the root cause for my issue as well, but this didn't solve my issue unfortunately.
I'll use the latest version tonight and see if I can reproduce the issue I'm experiencing.

I've tried to create a component in stackbliz called `MarkerForClustersCompnent2` to be able to change when the `updateCluster` is called for faster debug, but for some reason I couldn't make it work: If you can take a look at mfc2.ts file and see if you can add it as a component and still see the clusters - I can't make it work and I don't know why...

**Comment by HarelM** [comment]
OK, I think I'm on to something, but it's weird....
I have updated the stackblitz with multiple clusters using `*ngFor`
I have registered the `data` event to see that they don't get `isSourceLoaded=true` every time.
Move the map a bit to see the issue. In theory you should be seeing two clusters slightly overlap one another, in practice, sometimes you see only a single cluster until moving the map a bit.
I'm not sure it is related to this issue or a different one.
I see this in my code when initializing the clusters - the `isSourceLoaded` in my case is always `false` for the two clusters I'm using.
https://stackblitz.com/edit/ngx-mapbox-gl-issue-206-moveend?file=src/app/app.component.ts

Again, it might be a bug in my code, both mine and the one I just updated in stackblitz, but I swear I have an issue which is not trivial :-)

**Comment by Wykks** [comment]
Thanks for the repro!

Just simplified it a bit: https://stackblitz.com/edit/ngx-mapbox-gl-issue-206-moveend-msbe9u

Indeed, it seems like we cannot count on `event.isSourceLoaded` in some cases. Look like a bug in mapbox-gl. I may report that later...

As a workaround using `isSourceLoaded` seems to works fine.

Fix incoming !

**Comment by HarelM** [comment]
Thanks for the super quick response and fix! I'll update the library tonight-ish and let you know if this put this migration to rest :-)

**Comment by HarelM** [comment]
Seems like this last change has fixed my issue :-). Thanks a lot! I truly appreciate it.

**Comment by ShubhamJainSJ** [comment]
@HarelM @Wykks Can you please share the version number which addresses cluster overlap issue?

**Comment by HarelM** [comment]
This bug does not solve cluster overlap issue. It solve a problem to dynamically updating a cluster.
The above screen shot that represent an overlap is caused by the fact that there is more than one cluster.
I'm currently using version 4.4.2 which solves this issue. I haven't had time to upgrade my dependencies lately.
I had more than one cluster and had overlap issues. The solution for me was to migrate to a single source and thus a single cluster -> i.e. no overlaps.
